[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 200
verbosity = 5
[profile.default.fuzz]
runs = 1000

[rpc_endpoints]
BOT = "${BOT_RPC_URL}"
BOT_sepolia = "https://forno.BOT-sepolia.BOT-testnet.org"
botchain = "${BOTCHAIN_RPC_URL}"
[etherscan]
BOT_sepolia = { key = "any", url = "https://BOT-sepolia.blockscout.com/api/" }
BOT = { key = "${BOTSCAN_API_KEY}", url = "https://api.BOTscan.io/api" }
botchain = { key = "any", url = "https://scan.bohr.life/api", chain = 968 }